name: Sync issue to Azure DevOps

"on":
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - uses: franzdiebold/github-env-vars-action@v1.1.2
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "${{ env.GITHUB_REPOSITORY_OWNER }}"
          ado_project: "${{ secrets.ADO_PROJECT_NAME }}"
          ado_area_path: "${{ secrets.ADO_PROJECT_NAME }}\\${{ env.GITHUB_REPOSITORY_NAME }}"
          ado_wit: "Bug"
          ado_new_state: "New"
          ado_close_state: "Done"
          ado_bypassrules: true
